### ISSUE TITLE
vi test fails when using trackRequestProgress

### ISSUE THREAD

**Issue by subhashreerautray** [teil-one/fetch-api-progress#1]
When running the vi test getting the below error:

<img width="1176" alt="Screenshot 2024-01-31 at 11 18 24 AM" src="https://github.com/teil-one/fetch-api-progress/assets/42671265/406da420-2437-453b-94a7-2806b28513b6">

For test case we are trying to mock the function trackRequestProgress but getting the below error
TypeError: Cannot redefine property: trackRequestProgress

**Comment by sk-pub** [comment]
@subhashreerautray, [Blob.stream()](https://developer.mozilla.org/en-US/docs/Web/API/Blob/stream#browser_compatibility) is supported since Node.js 15.7.0. Which version of Node do you use? What is inside request.body that you pass to `trackRequestProgress`?

**Comment by sk-pub** [comment]
@subhashreerautray, it seems there is something wrong in the request.body that you pass to trackRequestProgress.
You can debug the code at https://github.com/teil-one/fetch-api-progress/blob/main/src/trackRequestProgress.ts#L84. Or simply inspect the value of request.body before passing the request to trackRequestProgress.
